### ISSUE TITLE
Plugin doesn't switch all styles

### ISSUE THREAD

**Issue by Slaaavo** [glmrvn/figma-dark-mode-plugin#20]
I started using this plugin, but I found out it does only about 80% of the work. For whatever reason, it doesn't change all the styles. It's really random too. I select a frame and it changes about 80% of the styles. Then I change some of those it hasn't, try again and it will change a few more and so on.

**Comment by glmrvn** [comment]
Hello. I pushed update today. Please check it out. Plugin updated automatically in Figma. Hope this solves this problem. 
If you have the same problem, please send me a link to a sample file.
